### ISSUE TITLE
Copying to clipboard doesn't work

### ISSUE THREAD

**Issue by emzywastaken** [NotAShelf/narnia#1]
Pressing enter to copy to clipboard doesn't copy to clipboard. In fact it empties my clipboard, Easter egg?. Im on wayland if that matters

https://github.com/user-attachments/assets/1baac3d0-a5ce-47cb-a746-9526312e5153

**Comment by NotAShelf** [comment]
This is a fault of libclipboard as far as I'm aware. I was working on fixing this, but could not yet figure out what is not working.

**Comment by emzywastaken** [comment]
> This is a fault of libclipboard as far as I'm aware. I was working on fixing this, but could not yet figure out what is not working.

Ok I've tested this, found that this is in fact due to me being on wayland(libclipboard limitation). It worked on X11 but even then there was a quirk. On X11 the clipboard is only set as long as the program is running 😛, or rather as long as `clipboard_c` is alive.

**Comment by emzywastaken** [comment]
Would you be ok with switching based on an environment variable. Maybe I can PR that

**Comment by NotAShelf** [comment]
Resolved in the master branch, do test it please :)

**Comment by emzywastaken** [comment]
> Resolved in the master branch, do test it please :)

hmm. Finished testing and still doesn't work, there's new behavior though :). On wayland copying takes some time maybe ~2s, On X11 copying is instant but breaks the clipboard? trying to paste after copying crashed my terminal. Would've attached a video but to lazy 😛. Why is working with clipboards this lame 😔

EDIT:
what da helly. Building with `zig build` in devshell was when copying on wayland was slow and with no result buut with `nix build` its fast again but with the same behavior as on X11. Also got `Warning: Could not initialize clipboard functionality` only with `zig build`

**Comment by NotAShelf** [comment]
I haven't tested x11, and frankly I am less interested in maintaining the x11 functionality. Users are welcome to use actually maintained protocols.

A little weird that the `zig build` and `nix build` behave differently though, we provide the same deps to both...

Edit: my X11 impl was mostly guesswork based on X11 programs based on GH search so not entirely surprised that it doesn't work. I have ideas to refactor the clipboard functionality into a separate library that the project imports, but it's not a dealbreaker since I have confirmed wayland to be working :)

**Comment by emzywastaken** [comment]
I also dont really care about X11, but copying on wayland doesn't even work for me, ig I forgot to mention that?. It still just empties my clipboard

**Comment by NotAShelf** [comment]
Odd, but cannot reproduce. Your clipboard manager might be mangling the entry.

Try <https://github.com/notashelf/stash>.

**Comment by emzywastaken** [comment]
Ok yeah it works with stash. Didn't even know a clipboard manager was a thing, never had to set one up. Another rafware I have to look into :)

**Comment by NotAShelf** [comment]
Always bet on rafware o7
